export {
  slugify,
  listAdminProducts,
  getAdminProduct,
  listCategoriesForAdmin,
  saveProduct,
  saveVariant,
  deactivateVariant,
  attachImage,
  detachImage,
  type ProductInput,
  type VariantInput,
  type SaveProductResult,
  type SaveVariantResult,
  type AdminActor as CatalogAdminActor,
} from './admin';
